name: RepoReloader
version: '${version}'
main: top.jaxlabs.repoReloader.RepoReloader
api-version: '1.21'
folia-supported: true
authors: [ Jack F. ]
permissions:
	reporeloader.admin.updates:
		description: Receive notifications about available repository plugin updates.
		default: op
